languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

# title = "Ioannis Polyzos"
# logo = "logo.jpg"
description = "NullBox.org official site!"
copyright = "© NullBox. All rights reseved."

dateFormat = "2 January 2006"

[author]
  name = "Null Box"
  image = "img/logo.png"
  #headline = "Taking the most out of your resources!"
  headline = "Unlocking Your Value In the Cloud - Together!"
  bio = "Software & Cloud Engineering Consultancy!"
  links = [
    { email = "mailto:contact@nullbox.org" },
    { github = "https://github.com/null-box/" },
    { twitter = "https://twitter.com/nullboxorg" },
    { facebook = "https://www.facebook.com/nullboxorg" },
    { calendar = "https://cal.com/ipolyzos" }
  ]

[share-links-active]
  twitter = true
  linkedin = true